### ISSUE TITLE
ValueError: unsupported datatype for array

### ISSUE THREAD

**Issue by kosarev** [CityAceE/sPycialist#2]
Just tried to run the emulator and got:
```
$ python3 spycialist.py 
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
START: 0000
END: 1E2F
Traceback (most recent call last):
  File "/home/kosarev/.local/lib/python3.8/site-packages/pygame/surfarray.py", line 87, in blit_array
    return numpysf.blit_array(surface, array)
AttributeError: 'NoneType' object has no attribute 'blit_array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spycialist.py", line 60, in <module>
    blitsurface()
  File "spycialist.py", line 38, in blitsurface
    pygame.surfarray.blit_array(screen, np.reshape(bits, (256, 384)).T)
  File "/home/kosarev/.local/lib/python3.8/site-packages/pygame/surfarray.py", line 90, in blit_array
    return numpysf.blit_array(surface, array)
  File "/home/kosarev/.local/lib/python3.8/site-packages/pygame/_numpysurfarray.py", line 79, in blit_array
    return array_to_surface(surface, array)
ValueError: unsupported datatype for array
```

Seems to be related to the code suggested in #1. Have no experience with pygame, so not sure what's wrong.

Tagging @svofski for visibility.

**Comment by CityAceE** [comment]
You probably forgot to install numpy library.
